DBCC CHECKIDENT (PMS_CHARGABLE, reseed, 0)

SELECT * FROM PMS_SERVICETYPE

--DRUG
--SHOP
--SERV
--PANAL
--NONE
--DF
--LIS
--VACC
--DEP
--STUDY
--MESS
--RIS
--BIO
--PACK

SELECT DISTINCT [DRUG ROUTE] FROM [KKU-MasterData]..['Chargable Items_DRUG$']
SELECT * FROM [KKU-PetMatrix]..PMS_DRUGROUTE
SELECT ROW_NUMBER() OVER (Order by [ITEM NAME]) AS [UID], [ITEM NAME], 
(CASE WHEN [DRUG ROUTE] = 'Ear cleans' THEN 9
	 WHEN [DRUG ROUTE] = 'Ear drop' THEN 11
	 WHEN [DRUG ROUTE] = 'Enema' THEN 10
	 WHEN [DRUG ROUTE] = 'Eye drop' THEN 7
	 WHEN [DRUG ROUTE] = 'Inhalation' THEN 15
	 WHEN [DRUG ROUTE] = 'Injection' THEN 2
	 WHEN [DRUG ROUTE] = 'Ointment' THEN 5
	 WHEN [DRUG ROUTE] = 'Oral' THEN 1
	 WHEN [DRUG ROUTE] = 'Past' THEN 4
	 WHEN [DRUG ROUTE] = 'Shower' THEN 8
	 WHEN [DRUG ROUTE] = 'Spot on' THEN 12
	 WHEN [DRUG ROUTE] = 'Spray' THEN 6  
	  WHEN [DRUG ROUTE] = 'Swallow/ Enema' THEN 13
	 WHEN [DRUG ROUTE] = 'Topical' THEN 14 END) [ROUTE ID],
	 RATE,'DRUG' AS SERVICE_TYPE,1 AS SERVICE_TYPE_ID
	 INTO _DRUGITEM
FROM [KKU-MasterData]..['Chargable Items_DRUG$']


DROP TABLE _DRUGITEM

--SELECT * FROM PMS_SERVICETYPE


SELECT * FROM [KKU-PetMatrix]..PMS_DRUGROUTE

SELECT * FROM [KKU-PetMatrix]..PMS_DRUGINSTRUCTIONUNIT
DELETE FROM [KKU-PetMatrix]..PMS_DRUGINSTRUCTIONUNIT WHERE ORG_ID = 2
DBCC CHECKIDENT (PMS_DRUGINSTRUCTIONUNIT, reseed, 0)

GO
INSERT INTO [dbo].[PMS_DRUGINSTRUCTIONUNIT]

--SELECT     [UNIT_UID]
--           ,[UNIT_TEXT]
--           ,[UNIT_TEXT_ENG]
--           ,[ORG_ID]
--           ,[CREATED_BY]
--           ,[CREATED_ON]
--           ,[LAST_MODIFIED_BY]
--           ,[LAST_MODIFIED_ON]
--           ,[IS_ACTIVE] FROM _DrugUnit

GO

SELECT * FROM PMS_DRUGROUTE 
DBCC CHECKIDENT (PMS_DRUGROUTE, reseed, 10)

SELECT * FROM _Chargable WHERE SERViCE_TYPE = 'DRUG'

SELECT * FROM [PetMatrix]..INV_ITEMDTL


DECLARE @UID AS INT
DECLARE @DUID AS INT
DECLARE @FINALUID AS VARCHAR(10)
SELECT @UID = COUNT(*) FROM _DrugItem
WHILE(@UID>0)
BEGIN
 SET @FINALUID = 'D' +'-' +@DUID;
 SET @DUID = @DUID +1;
 UPDATE _DrugItem SET UID = @DUID

 SET @UID = @UID -1;

END
DECLARE @numRows int,@i int
SET @numRows = (SELECT COUNT(*) FROM _DrugItem)
SET @i=1

WHILE @i<@numRows
BEGIN
    UPDATE _DrugItem SET [UID] = 'D' +'-' +[UID] WHERE [UID] = @i;
    SET @i=@i+1
END

SELECT COUNT(*),[ITEM NAME] FROM _DrugItem
GROUP BY [ITEM NAME]
HAVING COUNT(*)>1


SELECT CONVERT(VARCHAR(10),'D' +'-' +CONVERT(VARCHAR(10),[UID])) AS [FINAL_UID] FROM _DrugItem