USE [KKU-PetMatrix]
GO
--DRUG
INSERT INTO [dbo].[PMS_CHARGABLE]
           ([ITEM_UID]
           ,[ITEM_NAME]
           ,[SERVICE_TYPE]
           ,[SERVICE_TYPE_ID]
           ,[ROUTE_ID]
           ,[RATE]
           ,[IS_ACTIVE]
           ,[QTY]
           ,[ORG_ID]
   )
SELECT CONVERT(VARCHAR(10),'D' +'-' +CONVERT(VARCHAR(10),[UID])) AS [ITEM_UID],[ITEM NAME] AS [ITEM_NAME],
SERVICE_TYPE AS [SERVICE_TYPE],SERVICE_TYPE_ID AS [SERVICE_TYPE_ID],[ROUTE ID] AS [ROUTE_ID],RATE AS [RATE],
1 AS [IS_ACTIVE],100 AS [QTY],1 AS [ORG_ID] FROM _DrugItem
GO

INSERT INTO [dbo].[PMS_CHARGABLE]
           ([ITEM_UID]
           ,[ITEM_NAME]
		   ,[REPORT_HEADER]
           ,[SERVICE_TYPE]
           ,[SERVICE_TYPE_ID]
           ,[RATE]
		   ,[IS_PANEL]
           ,[IS_ACTIVE]
		   ,[UNITS]
           ,[QTY]
           ,[ORG_ID]
   )
SELECT [ITEM CODE] AS [ITEM_UID],[ITEM NAME] AS [ITEM_NAME],[REPORT HEADER] AS [REPORT_HEADER],
'LIS' AS [SERVICE_TYPE],7 AS [SERVICE_TYPE_ID],RATE AS [RATE],(CASE WHEN [IS PANEL] = 'NO' THEN 0 WHEN [IS PANEL] = 'YES' THEN 1 END) AS [IS_PANEL],
1 AS [IS_ACTIVE],[UNITS],0 AS [QTY],1 AS [ORG_ID] FROM [KKU-MasterData]..['Chargable Items_LIS$'] WHERE [ITEM NAME] IS NOT NULL
GO

--RIS

INSERT INTO [dbo].[PMS_CHARGABLE]
           ([ITEM_UID]
           ,[ITEM_NAME]
           ,[SERVICE_TYPE]
           ,[SERVICE_TYPE_ID]
           ,[RATE]
           ,[IS_ACTIVE]
           ,[QTY]
           ,[ORG_ID]
   )
SELECT CONVERT(VARCHAR(10),'R' +'-' +CONVERT(VARCHAR(10),ROW_NUMBER() OVER(ORDER BY [ITEM NAME]))) AS [ITEM_UID],[ITEM NAME] AS [ITEM_NAME],
'RIS' AS [SERVICE_TYPE],12 AS [SERVICE_TYPE_ID],RATE AS [RATE],
1 AS [IS_ACTIVE],0 AS [QTY],1 AS [ORG_ID] FROM [KKU-MasterData]..['Chargable Items_RIS$'] WHERE [ITEM NAME] IS NOT NULL
GO

--DF
INSERT INTO [dbo].[PMS_CHARGABLE]
           ([ITEM_UID]
           ,[ITEM_NAME]
           ,[SERVICE_TYPE]
           ,[SERVICE_TYPE_ID]
           ,[RATE]
           ,[IS_ACTIVE]
           ,[QTY]
           ,[ORG_ID]
   )
SELECT [ITEM CODE] AS [ITEM_UID],[ITEM NAME] AS [ITEM_NAME],
'DF' AS [SERVICE_TYPE],6 AS [SERVICE_TYPE_ID],RATE AS [RATE],
1 AS [IS_ACTIVE],0 AS [QTY],1 AS [ORG_ID] FROM [KKU-MasterData]..['Chargable Items_DF$'] WHERE [ITEM NAME] IS NOT NULL
GO

--DF
INSERT INTO [dbo].[PMS_CHARGABLE]
           ([ITEM_UID]
           ,[ITEM_NAME]
           ,[SERVICE_TYPE]
           ,[SERVICE_TYPE_ID]
           ,[RATE]
           ,[IS_ACTIVE]
           ,[QTY]
           ,[ORG_ID]
   )
SELECT CONVERT(VARCHAR(10),'STD' +'-' +CONVERT(VARCHAR(10),ROW_NUMBER() OVER(ORDER BY [ITEM_NAME]))) AS [ITEM_UID],[ITEM_NAME] AS [ITEM_NAME],
'STUDY' AS [SERVICE_TYPE],10 AS [SERVICE_TYPE_ID],RATE AS [RATE],
1 AS [IS_ACTIVE],0 AS [QTY],1 AS [ORG_ID] FROM [KKU-MasterData]..['Chargable Items_STUDY$'] WHERE [ITEM_NAME] IS NOT NULL
GO

--SERVICE
INSERT INTO [dbo].[PMS_CHARGABLE]
           ([ITEM_UID]
           ,[ITEM_NAME]
           ,[SERVICE_TYPE]
           ,[SERVICE_TYPE_ID]
           ,[RATE]
           ,[IS_ACTIVE]
           ,[QTY]
           ,[ORG_ID]
   )
SELECT CONVERT(VARCHAR(10),'SER' +'-' +CONVERT(VARCHAR(10),ROW_NUMBER() OVER(ORDER BY [ITEM NAME]))) AS [ITEM_UID],[ITEM NAME] AS [ITEM_NAME],
'SERV' AS [SERVICE_TYPE],3 AS [SERVICE_TYPE_ID],RATE AS [RATE],
1 AS [IS_ACTIVE],0 AS [QTY],1 AS [ORG_ID] FROM [KKU-MasterData]..['Chargable Items_SERVE$'] WHERE [ITEM NAME] IS NOT NULL
GO

--PANEL
INSERT INTO [dbo].[PMS_CHARGABLE]
           ([ITEM_UID]
           ,[ITEM_NAME]
           ,[SERVICE_TYPE]
           ,[SERVICE_TYPE_ID]
           ,[RATE]
           ,[IS_ACTIVE]
           ,[QTY]
           ,[ORG_ID]
   )
SELECT [ITEM CODE] AS [ITEM_UID],[ITEM NAME] AS [ITEM_NAME],
'PANAL' AS [SERVICE_TYPE],4 AS [SERVICE_TYPE_ID],RATE AS [RATE],
1 AS [IS_ACTIVE],0 AS [QTY],1 AS [ORG_ID] FROM [KKU-MasterData]..['Chargable Items_PANEL$'] WHERE [ITEM NAME] IS NOT NULL
GO

--NONE
INSERT INTO [dbo].[PMS_CHARGABLE]
           ([ITEM_UID]
           ,[ITEM_NAME]
           ,[SERVICE_TYPE]
           ,[SERVICE_TYPE_ID]
           ,[RATE]
           ,[IS_ACTIVE]
           ,[QTY]
           ,[ORG_ID]
   )
SELECT CONVERT(VARCHAR(10),'NN' +'-' +CONVERT(VARCHAR(10),ROW_NUMBER() OVER(ORDER BY [ITEM NAME]))) AS [ITEM_UID],[ITEM NAME] AS [ITEM_NAME],
'NONE' AS [SERVICE_TYPE],5 AS [SERVICE_TYPE_ID],RATE AS [RATE],
1 AS [IS_ACTIVE],0 AS [QTY],1 AS [ORG_ID] FROM [KKU-MasterData]..['Chargable Items_NONE$'] WHERE [ITEM NAME] IS NOT NULL
GO

--IPD
INSERT INTO [dbo].[PMS_CHARGABLE]
           ([ITEM_UID]
           ,[ITEM_NAME]
           ,[SERVICE_TYPE]
           ,[SERVICE_TYPE_ID]
           ,[RATE]
           ,[IS_ACTIVE]
           ,[QTY]
           ,[ORG_ID]
   )
SELECT CONVERT(VARCHAR(10),'IP' +'-' +CONVERT(VARCHAR(10),ROW_NUMBER() OVER(ORDER BY [ITEM_NAME]))) AS [ITEM_UID],[ITEM_NAME] AS [ITEM_NAME],
'IPD' AS [SERVICE_TYPE],15 AS [SERVICE_TYPE_ID],RATE AS [RATE],
1 AS [IS_ACTIVE],0 AS [QTY],1 AS [ORG_ID] FROM [KKU-MasterData]..['Chargable Items_IPD$'] WHERE [ITEM_NAME] IS NOT NULL
GO

SELECT * FROM [PMS_CHARGABLE] WHERE SERVICE_TYPE = 'IPD'

--Admission Reason
INSERT INTO [KKU-PetMatrix]..IP_ADMISSION_REASON(REASON_UID,REASON_TEXT,AMOUNT,ORG_ID)
SELECT CONVERT(VARCHAR(10),'AR' +'-' +CONVERT(VARCHAR(10),ROW_NUMBER() OVER(ORDER BY [Admission Reason]))) AS [REASON_UID],[Admission Reason] AS REASON_TEXT,
[Advance Amount] AS AMOUNT,1 AS ORG_ID
 FROM [KKU-MasterData]..['Admission Reason$']

 DBCC CHECKIDENT (IP_ADMISSION_REASON, reseed, 0)
SELECT * FROM [KKU-PetMatrix]..IP_ADMISSION_REASON


--IP Building
DBCC CHECKIDENT (IP_BUILDING, reseed, 0)

--IP Floor
DBCC CHECKIDENT (IP_Floor, reseed, 0)

--IP Ward
DBCC CHECKIDENT (IP_Ward, reseed, 0)

--IP Room Type
DBCC CHECKIDENT (IP_ROOMTYPE, reseed, 0)
INSERT INTO [dbo].[IP_ROOMTYPE]([ROOMTYPE_UID],[ROOMTYPE_TEXT],[ITEM_ID],ORG_ID)
SELECT CONVERT(VARCHAR(10),'RT' +'-' +CONVERT(VARCHAR(10),ROW_NUMBER() OVER(ORDER BY [Room Type name]))) AS [REASON_UID],[Room Type name] AS [ROOMTYPE_TEXT],
2513 AS ITEM_ID,1 AS ORG_ID
 FROM [KKU-MasterData]..['Room Type$']

 SELECT * FROM [KKU-MasterData]..['Room Type$']
 SELECT * FROM [KKU-PetMatrix]..IP_ROOMTYPE

 --Room
 SELECT * FROM IP_ROOM
 SELECT * FROM IP_WARD
 DBCC CHECKIDENT (IP_ROOM, reseed, 0)


INSERT INTO [KKU-PetMatrix]..IP_ADMISSION_REASON(REASON_UID,REASON_TEXT,AMOUNT,ORG_ID)
SELECT CONVERT(VARCHAR(10),'AR' +'-' +CONVERT(VARCHAR(10),ROW_NUMBER() OVER(ORDER BY [Admission Reason]))) AS [REASON_UID],[Admission Reason] AS REASON_TEXT,
[Advance Amount] AS AMOUNT,1 AS ORG_ID
 FROM [KKU-MasterData]..['Admission Reason$']

 --BED
 INSERT INTO [KKU-PetMatrix]..IP_BED(BED_UID,BED_TEXT,CAGE_ID,CAGE_NAME, ROOM_ID,BED_STATUS,ORG_ID)
SELECT CONVERT(VARCHAR(10),'BD' +'-' +CONVERT(VARCHAR(10),ROW_NUMBER() OVER(ORDER BY [Bed Name]))) AS [BED_UID],[Bed Name] AS BED_TEXT,
(CASE WHEN [Cage Name] = 'Small Size' THEN 1 
     WHEN [Cage Name] = 'Medium Size' THEN 2
	 WHEN [Cage Name] = 'Large Size' THEN 3  
	 WHEN [Cage Name] = 'Extra Large Size' THEN 4 END) AS CAGE_ID,[Cage Name] AS CAGE_NAME, 
1 AS ROOM_ID,'F' AS BED_STATUS,1 AS ORG_ID
 FROM [KKU-MasterData]..[Bed$]

DBCC CHECKIDENT (IP_BED, reseed, 0)

--SCHEDULE TYPE
DELETE FROM PMS_SCHEDULETYPE
DBCC CHECKIDENT (PMS_SCHEDULETYPE, reseed, 0)
SELECT * FROM [KKU-MasterData]..['Schedule Type$']
INSERT INTO PMS_SCHEDULETYPE(SCHEDULE_TYPE_UID,SCHEDULE_TYPE_TEXT,IS_ACTIVE,ORG_ID)
SELECT CONVERT(VARCHAR(10),'ST' +'-' +CONVERT(VARCHAR(10),ROW_NUMBER() OVER(ORDER BY [Appointment Type Name]))) AS [SCHEDULE_TYPE_UID],
[Appointment Type Name] AS SCHEDULE_TYPE_TEXT, 1 AS [IS_ACTIVE],1 AS [ORG_ID]
FROM [KKU-MasterData]..['Schedule Type$']

SELECT * FROM [PetMatrix]..PMS_CHARGABLE WHERE SERVICE_TYPE = 'LIS'

--USER DETAILS
SELECT * FROM HR_USER
DELETE FROM HR_USER
DBCC CHECKIDENT (HR_USER, reseed, 0)

INSERT INTO [dbo].[HR_USER]
           ([USER_UID],[USER_NAME],[JOB_TYPE],[TITLE_NLS],[FNAME_NLS],[LNAME_NLS]
           ,[TITLE_ENG],[FNAME_ENG],[LNAME_ENG],[GENDER],[EMAIL_PERSONAL],[EMAIL_OFFICIAL]
           ,[PHONE_HOME],[IS_ACTIVE],[ORG_ID],[TIMEZONE_ID],[IS_AUTO_REFRESH],[REFRESH_TIME])

SELECT CONVERT(VARCHAR(10),'U' +'-' +CONVERT(VARCHAR(10),ROW_NUMBER() OVER(ORDER BY [User Name]))) AS [USER_UID],
[User Name] AS [USER_NAME],(CASE WHEN [Job Type] = 'admin, vet' THEN 'A'
								WHEN [Job Type] = 'vet' THEN 'D'
								WHEN [Job Type] = 'Counter' THEN 'H'
								WHEN [Job Type] = 'Operator' THEN 'O'
								WHEN [Job Type] = 'Cashier' THEN 'C'
								WHEN [Job Type] = 'Drug' THEN 'P'
								WHEN [Job Type] = 'Cashier, operator' THEN 'C'
								WHEN [Job Type] = 'Lab' THEN 'L' END) AS [JOB_TYPE],

[Title (National Language)] AS [TITLE_NLS], [First Name (National Language)] AS [FNAME_NLS], [Last Name (National Language)] AS [LNAME_NLS],
[Title (English)] AS [TITLE_ENG], [First Name (English)] AS  [FNAME_ENG], [Last Name (English)] AS [LNAME_ENG],
(CASE WHEN [Gender] = 'female' THEN 'F'
	WHEN [Gender] = 'male' THEN 'M' END) AS [GENDER],Email AS [EMAIL_PERSONAL],
Email AS [EMAIL_OFFICIAL],[Phone Number] AS [PHONE_HOME],1 AS [IS_ACTIVE],1 AS [ORG_ID],'Indochina Time' AS [TIMEZONE_ID],0 AS [IS_AUTO_REFRESH], 60 AS [REFRESH_TIME] 
 FROM [KKU-MasterData]..['User Details$']

DELETE FROM GBL_GRANTROLE
DBCC CHECKIDENT (GBL_GRANTROLE, reseed, 0)

INSERT INTO [dbo].[GBL_GRANTROLE]
           ([ROLE_ID]
           ,[USER_ID]
           ,[ORG_ID])
SELECT (CASE WHEN JOB_TYPE = 'A' THEN 1
            WHEN JOB_TYPE = 'C' THEN 8
			WHEN JOB_TYPE = 'D' THEN 2
			WHEN JOB_TYPE = 'H' THEN 5
			WHEN JOB_TYPE = 'L' THEN 6
			WHEN JOB_TYPE = 'O' THEN 9
			WHEN JOB_TYPE = 'P' THEN 4 
			WHEN JOB_TYPE IS NULL THEN 1 END) AS ROlE_ID,[USER_ID],1 AS ORG_ID
		    FROM HR_USER 


--Role
DBCC CHECKIDENT (GBL_ROLE, reseed, 8)

SELECT DISTINCT JOB_TYPE FROM HR_USER
SELECT DISTINCT [Job Type] FROM [KKU-MasterData]..['User Details$']
SELECT * FROM GBL_ROLE

--Monitoring Object
DBCC CHECKIDENT ([IP_MONITORINGOBJECTS], reseed, 0)
INSERT INTO [dbo].[IP_MONITORINGOBJECTS]
           ([OBJECT_UID]
           ,[OBJECT_TEXT]
           ,[ORG_ID])
SELECT CONVERT(VARCHAR(10),'OBJ' +'-' +CONVERT(VARCHAR(10),ROW_NUMBER() OVER(ORDER BY [Object Text]))) AS [OBJECT_UID],
[Object Text],1 AS ORG_ID
FROM [KKU-MasterData]..['Monitoring Object$']

--Breed

SELECT * FROM [IP_MONITORINGOBJECTS]

--SELECT * FROM  [KKU-MasterData]..['Chargable Items_DF$']
--SELECT DISTINCT [DRUG ROUTE] FROM [KKU-MasterData]..['Chargable Items_DRUG$']

--SELECT * FROM [KKU-MasterData]..['Chargable Items_VACCINE$']
--SELECT * FROM [KKU-MasterData]..['Chargable Items_STUDY$']
--SELECT * FROM [KKU-MasterData]..['Chargable Items_SERVE$']
--SELECT * FROM [KKU-MasterData]..['Chargable Items_Shop$']
--SELECT * FROM [KKU-MasterData]..['Chargable Items_RIS$']
--SELECT * FROM [KKU-MasterData]..['Chargable Items_PANEL$']
--SELECT * FROM [KKU-MasterData]..['Chargable Items_NONE$']
--SELECT * FROM [KKU-MasterData]..['Chargable Items_LIS$']
SELECT * FROM [KKU-MasterData]..['Chargable Items_IPD$']

SELECT * FROM PMS_SERVICETYPE

DBCC CHECKIDENT (PMS_CHARGABLE, reseed, 2511)

SELECT IS_PANEL FROM [PetMatrix]..PMS_CHARGABLE WHERE SERVICE_TYPE = 'LIS' AND IS_PANEL = 1

SELECT * FROM PMS_CHARGABLE

SELECT * FROM HR_USER

--Advance Details
SELECT * FROM FIN_ADVANCEPAYMENTDETAILS
DELETE FROM FIN_ADVANCEPAYMENTDETAILS
DBCC CHECKIDENT (FIN_ADVANCEPAYMENTDETAILS, reseed, 0)

-- FIN_INVOICE
SELECT * FROM FIN_INVOICE
DELETE FROM FIN_INVOICE
DBCC CHECKIDENT (FIN_INVOICE, reseed, 0)

--[dbo].[FIN_INVOICEDTL]
SELECT * FROM [FIN_INVOICEDTL]
DELETE FROM [FIN_INVOICEDTL]
DBCC CHECKIDENT ([FIN_INVOICEDTL], reseed, 0)

--FIN_PAYMENT
SELECT * FROM FIN_PAYMENT
DELETE FROM FIN_PAYMENT
DBCC CHECKIDENT (FIN_PAYMENT, reseed, 0)

--GBL_SESSION
SELECT * FROM GBL_SESSION
DELETE FROM GBL_SESSION
DBCC CHECKIDENT (GBL_SESSION, reseed, 0)

--PMR_ADMISSION
SELECT * FROM PMR_ADMISSION
DELETE FROM PMR_ADMISSION
DBCC CHECKIDENT (PMR_ADMISSION, reseed, 0)

--PMR_CONSULTATION
SELECT * FROM PMR_CONSULTATION
DELETE FROM PMR_CONSULTATION
DBCC CHECKIDENT (PMR_CONSULTATION, reseed, 0)

--Client
SELECT * FROM PMS_Client
DELETE FROM PMS_Client
DBCC CHECKIDENT (PMS_CLIENT, reseed, 0)

--Patient
SELECT * FROM PMS_PATIENT
DELETE FROM PMS_PATIENT
DBCC CHECKIDENT (PMS_PATIENT, reseed, 0)

--Patient Allergy
SELECT * FROM [PMS_PATIENTALLERGY]
DELETE FROM [PMS_PATIENTALLERGY]
DBCC CHECKIDENT ([PMS_PATIENTALLERGY], reseed, 0)


--Session
DELETE FROM [dbo].[GBL_SESSION]
DBCC CHECKIDENT ([GBL_SESSION], reseed, 0)

--Sequence
SELECT * FROM GBL_SEQUENCES
DELETE FROM GBL_SEQUENCES
DBCC CHECKIDENT (GBL_SEQUENCES, reseed, 0)

--INSERT INTO GBL_SEQUENCES(SEQ_NAME,SEED,INCR,CURR_VAL,ORG_ID)
GO
--SELECT SEQ_NAME,1 AS SEED,1 AS INCR,10000 AS CURR_VAL,1 AS ORG_ID FROM _Sequence WHERE ORG_ID = 1

--Invoice
DBCC CHECKIDENT ([FIN_INVOICE], reseed, 0)

--Invoice Detail
DBCC CHECKIDENT ([FIN_INVOICEDTL], reseed, 0)

--Payment
DBCC CHECKIDENT ([FIN_PAYMENT], reseed, 0)

--Package
DBCC CHECKIDENT ([GBL_PACKAGE], reseed, 0)

--Generic and Service
DBCC CHECKIDENT ([INV_GENERICITEM], reseed, 0)

--Stock Transaction
DELETE FROM [dbo].[INV_STOCKTRANSACTION]
DBCC CHECKIDENT ([INV_STOCKTRANSACTION], reseed, 0)

--Item Stock
DELETE FROM [dbo].[INV_ITEMSTOCK]
DBCC CHECKIDENT ([INV_ITEMSTOCK], reseed, 0)

--Vendor 
DELETE FROM [dbo].[INV_VENDORS]
DBCC CHECKIDENT ([INV_VENDORS], reseed, 0)

--PO
DELETE FROM INV_PO
DBCC CHECKIDENT (INV_PO, reseed, 0)

--Wishlist
DELETE FROM [dbo].[INV_WISHLIST]
DBCC CHECKIDENT ([INV_WISHLIST], reseed, 0)

--Operation Activity
SELECT * FROM [dbo].[IP_OPERATIONACTIVITY]
DELETE FROM [dbo].[IP_OPERATIONACTIVITY]
DBCC CHECKIDENT ([IP_OPERATIONACTIVITY], reseed, 0)

--Patient Monitoring
SELECT * FROM [dbo].[IP_PATIENTMONITORING]
DELETE FROM [dbo].[IP_PATIENTMONITORING]
DBCC CHECKIDENT ([IP_PATIENTMONITORING], reseed, 0)

--Patient Monitoring detail
SELECT * FROM [dbo].[IP_PATIENTMONITORINGDTL]
DBCC CHECKIDENT ([IP_PATIENTMONITORINGDTL], reseed, 0)

--[dbo].[LIS_EXAMPANELRESULT]
SELECT * FROM [LIS_EXAMPANELRESULT]
DBCC CHECKIDENT ([LIS_EXAMPANELRESULT], reseed, 0)

--[LIS_EXAMPANELSTRUCTURE]
SELECT * FROM [dbo].[LIS_EXAMPANELSTRUCTURE]
DBCC CHECKIDENT ([LIS_EXAMPANELSTRUCTURE], reseed, 0)

--[LIS_EXAMRESULT]
DBCC CHECKIDENT ([LIS_EXAMRESULT], reseed, 0)

SELECT * FROM [dbo].[LIS_SAMPLECOLLECTION]

SELECT * FROM [dbo].[LIS_UNITEXAM]

--[dbo].[PMR_ADMISSION]

SELECT * FROM [PMR_ADMISSION]
DBCC CHECKIDENT ([PMR_ADMISSION], reseed, 0)

--[dbo].[PMR_CONSULTATION]

SELECT * FROM [PMR_CONSULTATION]
DELETE FROM [PMR_CONSULTATION]
DBCC CHECKIDENT ([PMR_CONSULTATION], reseed, 0)

--[dbo].[PMR_DOCUMENT]
SELECT * FROM [dbo].[PMR_DOCUMENT]
DBCC CHECKIDENT ([PMR_DOCUMENT], reseed, 0)

--[dbo].[PMR_FAVORITE]
SELECT * FROM [dbo].[PMR_FAVORITE]
DBCC CHECKIDENT ([PMR_FAVORITE], reseed, 0)

--Order
SELECT * FROM [dbo].[PMR_ORDER]
DELETE FROM [PMR_ORDER]
DBCC CHECKIDENT ([PMR_ORDER], reseed, 0)

--Order details
SELECT * FROM [dbo].[PMR_ORDERDTL]
DELETE FROM [PMR_ORDERDTL]
DBCC CHECKIDENT ([PMR_ORDERDTL], reseed, 0)

--[dbo].[PMR_PATIENTDIAGNOSES]
SELECT * FROM [dbo].[PMR_PATIENTDIAGNOSES]
DELETE FROM [PMR_PATIENTDIAGNOSES]
DBCC CHECKIDENT ([PMR_PATIENTDIAGNOSES], reseed, 0)

--[dbo].[PMR_PATIENTOPERATION]
SELECT * FROM [PMR_PATIENTOPERATION]
DELETE FROM [PMR_PATIENTOPERATION]
DBCC CHECKIDENT ([PMR_PATIENTOPERATION], reseed, 0)

--[dbo].[PMR_PATIENTOPERATIONDTL]
SELECT * FROM [dbo].[PMR_PATIENTOPERATIONDTL]
DELETE FROM [dbo].[PMR_PATIENTOPERATIONDTL]
DBCC CHECKIDENT ([PMR_PATIENTOPERATIONDTL], reseed, 0)

--[dbo].[PMR_PATIENTPROBLEM]
SELECT * FROM [dbo].PMR_PATIENTPROBLEM
DELETE FROM [dbo].PMR_PATIENTPROBLEM
DBCC CHECKIDENT (PMR_PATIENTPROBLEM, reseed, 0)

--[dbo].[PMR_PATIENTVISIT]
SELECT * FROM [dbo].PMR_PATIENTVISIT
DELETE FROM [dbo].PMR_PATIENTVISIT

--[dbo].[PMR_PATIENTVITALSIGN]
SELECT * FROM [dbo].PMR_PATIENTVITALSIGN
DELETE FROM [dbo].PMR_PATIENTVITALSIGN
DBCC CHECKIDENT (PMR_PATIENTVITALSIGN, reseed, 0)

--[dbo].[PMR_SCHEDULE]
SELECT * FROM [dbo].[PMR_SCHEDULE]
DELETE FROM [dbo].[PMR_SCHEDULE]
DBCC CHECKIDENT ([PMR_SCHEDULE], reseed, 0)

--[dbo].[PMS_ALLERGY]
SELECT * FROM [dbo].[PMS_ALLERGY]

SELECT * FROM [dbo].[PMS_DRUGDIRECTION]

SELECT * FROM [dbo].[PMS_DRUGDURATION]

SELECT * FROM [dbo].[PMS_PROBLEM]

--[dbo].[RIS_EXAMRESULTTEMPLATE]
SELECT * FROM [dbo].RIS_EXAMRESULTTEMPLATE
DELETE FROM [dbo].RIS_EXAMRESULTTEMPLATE
DBCC CHECKIDENT (RIS_EXAMRESULTTEMPLATE, reseed, 0)

--[dbo].[[RIS_EXAMTEMPLATEMAPPING]]
SELECT * FROM [dbo].[RIS_EXAMTEMPLATEMAPPING]
DELETE FROM [dbo].[RIS_EXAMTEMPLATEMAPPING]
DBCC CHECKIDENT ([RIS_EXAMTEMPLATEMAPPING], reseed, 0)

--Drug Instruction
SELECT * FROM [dbo].[PMS_DRUGINSTRUCTION]
DELETE FROM [dbo].[PMS_DRUGINSTRUCTION]
DBCC CHECKIDENT ([PMS_DRUGINSTRUCTION], reseed, 0)

--Sample Collection
SELECT * FROM [dbo].[LIS_SAMPLECOLLECTION]
DELETE FROM [dbo].[LIS_SAMPLECOLLECTION]
DBCC CHECKIDENT ([LIS_SAMPLECOLLECTION], reseed, 0)

--Rollback

SELECT * FROM PMR_ORDER

SELECT * FROM PMS_CHARGABLE

INSERT INTO INV_ITEMDTL(ITEM_ID,ITEM_COST,IN_HAND,WARNING_LEVEL,REORDER_QTY,ORG_ID)
SELECT ITEM_ID,RATE,QTY,10,1000,1 FROM PMS_CHARGABLE WHERE SERVICE_TYPE IN('DRUG','VACC','SHOP')

INSERT INTO INV_ITEMSTOCK(ITEM_ID,SL_NO,QTY,PRICE,IN_HAND,ORG_ID)
SELECT ITEM_ID,1,100,RATE,100,1 FROM PMS_CHARGABLE WHERE SERVICE_TYPE IN('DRUG','VACC','SHOP')

INSERT INTO INV_STOCKTRANSACTION(ITEM_STOCK_ID,QTY,ORG_ID)
SELECT ITEM_STOCK_ID,QTY,1 FROM INV_ITEMSTOCK


SELECT * FROM INV_ITEMDTL
SELECT * FROM INV_ITEMSTOCK
SELECT * FROM INV_STOCKTRANSACTION

UPDATE PMS_CHARGABLE SET IS_ACTIVE = 1 WHERE SERVICE_TYPE = 'VACC'

SELECT IS_ACTIVE FROM PMS_CHARGABLE WHERE SERVICE_TYPE = 'VACC'
SELECT IS_ACTIVE,QTY FROM PMS_CHARGABLE WHERE SERVICE_TYPE = 'NONE'

UPDATE INV_ITEMDTL SET IN_HAND = 100 WHERE ITEM_ID IN(SELECT ITEM_ID FROM PMS_CHARGABLE WHERE SERVICE_TYPE = 'VACC' )

SELECT * FROM INV_ITEMSTOCK WHERE ITEM_ID IN(SELECT ITEM_ID FROM PMS_CHARGABLE WHERE SERVICE_TYPE = 'VACC' )

SELECT * FROM [PetMatrix]..PMS_SERVICETYPE 
SELECT * FROM [KKU-PetMatrix]..PMS_SERVICETYPE 

UPDATE [KKU-PetMatrix]..INV_ITEMSTOCK SET IS_ACTIVE = 1

SELECT SERVICE_TYPE_ID FROM PMS_CHARGABLE WHERE SERVICE_TYPE = 'DRUG'


SELECT * FROM [PetMatrix]..PMS_SCHEDULETYPE 
SELECT * FROM [KKU-PetMatrix]..PMS_SCHEDULETYPE 

SELECT * FROM [PetMatrix]..IP_ADMISSION_REASON 
SELECT * FROM [KKU-PetMatrix]..IP_ADMISSION_REASON 

SELECT * FROM [KKU-PetMatrix]..PMR_SCHEDULE
SELECT * FROM [PetMatrix]..FIN_ADVANCEPAYMENTDETAILS 
