----------BEGIN TRAN
----------DELETE FROM FIN_PAYMENT
----------DELETE FROM FIN_ADVANCEPAYMENTDETAILS
----------DELETE FROM PMS_DRUGINSTRUCTION
----------DELETE FROM [dbo].[RIS_EXAMRESULT]
----------DELETE FROM [dbo].[PMR_ADMISSION]
----------DELETE FROM LIS_SAMPLECOLLECTION
----------DELETE FROM PMR_DOCUMENT
----------DELETE FROM PMS_PATIENTALLERGY
----------DELETE FROM PMR_ORDERDTL
----------DELETE FROM FIN_INVOICEDTL
----------DELETE FROM FIN_INVOICE
----------DELETE FROM PMR_ORDER
----------DELETE FROM PMR_PATIENTVITALSIGN
----------DELETE FROM PMR_PATIENTPROBLEM
----------DELETE FROM PMR_PATIENTDIAGNOSES
----------DELETE FROM PMR_CONSULTATION
----------DELETE FROM PMR_PATIENTVISIT
----------DELETE FROM PMS_PATIENT
----------DELETE FROM PMS_CLIENT

----------COMMIT
----------ROLLBACK


--Payment TABLE
SELECT * FROM FIN_PAYMENT
SELECT * FROM FIN_ADVANCEPAYMENTDETAILS
SELECT * FROM PMS_DRUGINSTRUCTION
SELECT * FROM PMR_ORDERDTL
SELECT * FROM FIN_INVOICEDTL
SELECT * FROM FIN_INVOICE
SELECT * FROM PMR_ORDER
SELECT * FROM PMR_PATIENTVITALSIGN
SELECT * FROM PMR_PATIENTPROBLEM
SELECT * FROM PMR_PATIENTDIAGNOSES
SELECT * FROM PMR_CONSULTATION
SELECT * FROM PMR_PATIENTVISIT
SELECT * FROM PMS_PATIENT
SELECT * FROM PMS_CLIENT

-------------------User Information------------------------------------
SELECT * FROM HR_USER
SELECT * FROM GBL_GRANTROLE
SELECT * FROM GBL_ROLE
SELECT * FROM GBL_ROLEDTL





