SELECT * FROM [KKU-PetMatrix]..PMS_CHARGABLE WHERE SERVICE_TYPE = 'DRUG'

SELECT * FROM [KKU-PetMatrix]..PMS_CHARGABLE

DELETE FROM [KKU-PetMatrix]..PMS_CHARGABLE

SELECT * INTO _REFRANGE FROM [KKU-PetMatrix]..LIS_EXAMREFRANGE

DELETE FROM [KKU-PetMatrix]..LIS_EXAMREFRANGE

SELECT * INTO _PanelStructure FROM [KKU-PetMatrix]..LIS_EXAMPANELSTRUCTURE

DELETE FROM [KKU-PetMatrix]..LIS_EXAMPANELSTRUCTURE


SELECT * FROM  [KKU-MasterData]..['Chargable Items_DF$']
SELECT DISTINCT [DRUG ROUTE] FROM [KKU-MasterData]..['Chargable Items_DRUG$']

--SELECT * INTO _ItemDetail FROM INV_ITEMDTL

--DELETE FROM INV_ITEMDTL
--SELECT COUNT(*) FROM PMS_CHARGABLE

--SELECT * FROM GBL_PACKAGEDTL
--DELETE FROM GBL_PACKAGEDTL

--DELETE FROM INV_PODTL
--DELETE FROM INV_WISHLIST

--DELETE FROM INV_VENDORITEMS

SELECT * INTO _RoomType FROM IP_ROOMTYPE
DELETE FROM IP_ROOMTYPE

SELECT * INTO _Room FROM IP_ROOM
DELETE FROM IP_ROOM

SELECT * INTO _Bed FROM IP_BED
DELETE FROM IP_BED