DBCC CHECKIDENT (PMS_CHARGABLE, reseed, 0)

SELECT * FROM PMS_SERVICETYPE

--DRUG
--SHOP
--SERV
--PANAL
--NONE
--DF
--LIS
--VACC
--DEP
--STUDY
--MESS
--RIS
--BIO
--PACK

SELECT DISTINCT [DRUG ROUTE] FROM [KKU-MasterData]..['Chargable Items_DRUG$']
SELECT * FROM [KKU-PetMatrix]..PMS_DRUGROUTE

SELECT * FROM [KKU-PetMatrix]..PMS_DRUGINSTRUCTIONUNIT
DELETE FROM [KKU-PetMatrix]..PMS_DRUGINSTRUCTIONUNIT WHERE ORG_ID = 2
DBCC CHECKIDENT (PMS_DRUGINSTRUCTIONUNIT, reseed, 0)

GO
INSERT INTO [dbo].[PMS_DRUGINSTRUCTIONUNIT]

SELECT     [UNIT_UID]
           ,[UNIT_TEXT]
           ,[UNIT_TEXT_ENG]
           ,[ORG_ID]
           ,[CREATED_BY]
           ,[CREATED_ON]
           ,[LAST_MODIFIED_BY]
           ,[LAST_MODIFIED_ON]
           ,[IS_ACTIVE] FROM _DrugUnit

GO

SELECT * FROM DRUG