DECLARE @UID AS INT
DECLARE @DUID AS INT
DECLARE @FINALUID AS VARCHAR(10)
SELECT @UID = COUNT(*) FROM _DrugItem
WHILE(@UID>0)
BEGIN
 SET @FINALUID = 'D' +'-' +@DUID;
 SET @DUID = @DUID +1;
 UPDATE _DrugItem SET UID = @DUID

 SET @UID = @UID -1;

END
DECLARE @numRows int,@i int
SET @numRows = (SELECT COUNT(*) FROM _DrugItem)
SET @i=1

WHILE @i<@numRows
BEGIN
    UPDATE _DrugItem SET [UID] = 'D' +'-' +[UID] WHERE [UID] = @i;
    SET @i=@i+1
END

SELECT COUNT(*),[ITEM NAME] FROM _DrugItem
GROUP BY [ITEM NAME]
HAVING COUNT(*)>1


SELECT CONVERT(VARCHAR(10),'D' +'-' +CONVERT(VARCHAR(10),[UID])) AS [FINAL_UID] FROM _DrugItem