CREATE OR REPLACE FUNCTION public.fnrad_performancestatus(p_start_date date, p_end_date date, p_user_id bigint)
 RETURNS TABLE("CATEGORY" text, "SERIES" text, "VALUE" bigint)
 LANGUAGE sql
AS $function$
SELECT "STATUS", '0' AS "SERIS", count("ACCESSION_NO") AS "VALUE"
FROM (
SELECT 
"ACCESSION_NO",
CASE WHEN "DIFF"<="TAT" THEN 'On TIme'
ELSE 'Belatedly' END AS "STATUS", "TAT", "DIFF"
FROM (
SELECT
"RIS_ORDERDTL"."ACCESSION_NO",
"RIS_ORDERDTL"."ASSIGNED_BY" ,
"RIS_ORDERDTL"."ASSIGNED_TO" ,
"RIS_ORDERDTL"."ASSIGNED_TIMESTAMP",
"RIS_EXAMRESULT"."FINALIZED_BY" ,
"RIS_EXAMRESULT"."FINALIZED_ON",
abs((EXTRACT(EPOCH FROM "RIS_EXAMRESULT"."FINALIZED_ON") - EXTRACT(EPOCH FROM "RIS_ORDERDTL"."ASSIGNED_TIMESTAMP"))/3600) "DIFF",
--"RIS_EXAMRESULT"."FIRSTFINALIZED_ON",
"GBL_TATSETUP"."MAX_HOUR" AS "TAT"
FROM 
"RIS_ORDER"
JOIN "RIS_ORDERDTL" ON "RIS_ORDER"."ORDER_ID" = "RIS_ORDERDTL"."ORDER_ID"
JOIN "RIS_EXAMRESULT" ON "RIS_ORDERDTL"."ORDER_ID" = "RIS_EXAMRESULT"."ORDER_ID"
LEFT JOIN "GBL_TATSETUP" ON "GBL_TATSETUP"."TATSETUP_ID" = "RIS_ORDERDTL"."TATSETUP_ID"
WHERE 
"RIS_ORDERDTL"."STATUS"= 'F' 
AND "RIS_EXAMRESULT"."FINALIZED_BY" =  p_user_id
AND ("RIS_EXAMRESULT"."FINALIZED_ON"::date BETWEEN p_start_date AND p_end_date)
) AS main
) AS main2 GROUP BY "STATUS"
ORDER BY "VALUE" DESC
$function$
;
