CREATE OR REPLACE FUNCTION public.fnrad_finalized(p_start_date date, p_end_date date, p_user_id bigint)
 RETURNS TABLE("CATEGORY" text, "SERIES" text, "VALUE" numeric)
 LANGUAGE sql
AS $function$
SELECT "CATEGORY", "SERIES", COALESCE("VALUE",0) AS "VALUE"--, "CVALUE", "CVALUE2"
FROM (
SELECT 
"RIS_SERVICETYPE"."SERVICE_TYPE_TEXT" AS "CATEGORY",
0 AS "SERIES",
COALESCE(count("RIS_ORDERDTL"."ACCESSION_NO"),0) AS "VALUE"
FROM "RIS_ORDER"        
JOIN "RIS_ORDERDTL"    ON "RIS_ORDER"."ORDER_ID" = "RIS_ORDERDTL"."ORDER_ID"
JOIN "RIS_EXAMRESULT"   ON "RIS_ORDERDTL"."ORDER_ID" = "RIS_EXAMRESULT"."ORDER_ID"
JOIN "RIS_SERVICETYPE"  ON "RIS_SERVICETYPE"."SERVICE_TYPE_ID" = "RIS_ORDERDTL"."SERVICE_TYPE"
WHERE "RIS_ORDERDTL"."STATUS"= 'F' 
and "RIS_EXAMRESULT"."FINALIZED_BY" = p_user_id
AND ("RIS_EXAMRESULT"."FINALIZED_ON"::date between p_start_date and p_end_date)
GROUP BY "RIS_SERVICETYPE"."SERVICE_TYPE_TEXT"

UNION 

SELECT 
'Total Finalized' AS "CATEGORY",
'1' AS "SERIES",
COALESCE(count("RIS_ORDERDTL"."ACCESSION_NO"),0) AS "VALUE"
FROM "RIS_ORDER"        
JOIN "RIS_ORDERDTL"    ON "RIS_ORDER"."ORDER_ID" = "RIS_ORDERDTL"."ORDER_ID"
JOIN "RIS_EXAMRESULT"   ON "RIS_ORDERDTL"."ORDER_ID" = "RIS_EXAMRESULT"."ORDER_ID"
JOIN "RIS_SERVICETYPE"  ON "RIS_SERVICETYPE"."SERVICE_TYPE_ID" = "RIS_ORDERDTL"."SERVICE_TYPE"
WHERE "RIS_ORDERDTL"."STATUS"= 'F' 
and "RIS_EXAMRESULT"."FINALIZED_BY" = p_user_id
AND ("RIS_EXAMRESULT"."FINALIZED_ON"::date between p_start_date and p_end_date)
) AS main 
ORDER BY "SERIES" desc, "CATEGORY"
$function$
;
