CREATE OR REPLACE FUNCTION public.fnrad_sitewisereportingtypebar(p_start_date date, p_end_date date, p_user_id bigint)
 RETURNS TABLE("CATEGORY" text, "SERIES" text, "VALUE" bigint)
 LANGUAGE sql
AS $function$
SELECT 
"GBL_ENV"."ORG_NAME" AS "CATEGORY", 
"RIS_SERVICETYPE"."SERVICE_TYPE_TEXT" AS "SERIES",
count("RIS_ORDERDTL"."ACCESSION_NO") AS "VALUE" -- "VALUE" 
FROM "RIS_ORDER"        
JOIN "RIS_ORDERDTL"    ON "RIS_ORDER"."ORDER_ID" = "RIS_ORDERDTL"."ORDER_ID"
JOIN "RIS_EXAMRESULT"   ON "RIS_ORDERDTL"."ORDER_ID" = "RIS_EXAMRESULT"."ORDER_ID"
JOIN "RIS_SERVICETYPE"  ON "RIS_SERVICETYPE"."SERVICE_TYPE_ID" = "RIS_ORDERDTL"."SERVICE_TYPE"
JOIN "GBL_ENV"          ON "GBL_ENV"."ORG_ID" = "RIS_ORDER"."ORG_ID"
WHERE 
"RIS_ORDERDTL"."STATUS"= 'F' 
AND "RIS_EXAMRESULT"."FINALIZED_BY" =  p_user_id
AND ("RIS_EXAMRESULT"."FINALIZED_ON"::date BETWEEN p_start_date AND p_end_date)
GROUP BY "RIS_SERVICETYPE"."SERVICE_TYPE_TEXT","GBL_ENV"."ORG_NAME"
ORDER BY "RIS_SERVICETYPE"."SERVICE_TYPE_TEXT","GBL_ENV"."ORG_NAME"
$function$
;
