-- Local variables
DECLARE @CLIENT_ID AS INT = 1;
DECLARE @PATIENT_ID AS INT = 1;
DECLARE @INVOICE_ID AS INT = 1;
DECLARE @VISIT_NO AS NVARCHAR(30) = '';

DELETE FROM FIN_ADVANCEPAYMENTDETAILS WHERE CLIENT_ID = @CLIENT_ID;
DELETE FROM FIN_PAYMENT WHERE INV_ID = @INVOICE_ID;
DELETE FROM FIN_INVOICEDTL WHERE INV_ID = @INVOICE_ID;
DELETE FROM FIN_INVOICE WHERE INV_ID = @INVOICE_ID;

DELETE FROM PMR_ORDERDTL WHERE ORDER_ID = (SELECT ORDER_ID FROM PMR_ORDER WHERE VISIT_NO = @VISIT_NO);
DELETE FROM PMR_ORDER WHERE VISIT_NO = @VISIT_NO;

--delete from PMR_ADMISSION;

DELETE FROM PMR_PATIENTPROBLEM WHERE PATIENT_ID = @PATIENT_ID;
DELETE FROM PMR_PATIENTDIAGNOSES WHERE PATIENT_ID = @PATIENT_ID;
DELETE FROM PMR_PATIENTVISIT WHERE PATIENT_ID = @PATIENT_ID;
DELETE FROM PMR_PATIENTOPERATIONDTL WHERE OPERATION_ID = (SELECT OPERATION_ID FROM PMR_PATIENTOPERATION WHERE PATIENT_ID = @PATIENT_ID);
DELETE FROM PMR_PATIENTOPERATION WHERE PATIENT_ID = @PATIENT_ID;

DELETE FROM PMR_CONSULTATION WHERE PATIENT_ID = @PATIENT_ID;
DELETE FROM PMR_PATIENTVITALSIGN WHERE PATIENT_ID = @PATIENT_ID;
DELETE FROM PMR_SCHEDULE WHERE PATIENT_ID = @PATIENT_ID;

DELETE FROM PMS_PATIENTALLERGY WHERE PATIENT_ID = @PATIENT_ID;
DELETE FROM PMS_PATIENT WHERE PATIENT_ID = @PATIENT_ID;
DELETE FROM PMS_CLIENT WHERE CLIENT_ID = @CLIENT_ID;
