DECLARE @ORG_ID INT;
SET
select * from PMS_SPECIES where ORG_ID=@ORG_ID
select * from PMS_BREED

--- species
INSERT INTO PMS_SPECIES(SPECIES_UID, SPECIES_TEXT, SPECIES_NAME, SPECIES_DESC, IS_ACTIVE, ORG_ID)
Select SPECIES_UID, SPECIES_TEXT, SPECIES_NAME, SPECIES_DESC, 1, @ORG_ID from PMS_SPECIES where ORG_ID = 1

--- breed
INSERT INTO PMS_BREED(BREED_TEXT,BREED_DESC,SPECIES_ID,IS_ACTIVE,ORG_ID)
select BREED_TEXT,BREED_DESC,SPECIES_ID, 1, @ORG_ID from PMS_BREED where ORG_ID = 1

--- color
INSERT INTO PMS_PETCOLOR (COLOR_TEXT,COLOR_DESC,IS_ACTIVE,ORG_ID)
Select COLOR_TEXT,COLOR_DESC, 1, @ORG_ID from PMS_PETCOLOR where ORG_ID = 1

--- location
INSERT INTO INV_LOCATION(LOCATION_NAME, LOCATION_ALIAS, PHONE_NO, LOCATION_TYPE, ORG_ID, IS_ACTIVE)
select LOCATION_NAME, LOCATION_ALIAS, PHONE_NO, LOCATION_TYPE, @ORG_ID, 1 from INV_LOCATION where ORG_ID = 1

--- floor
INSERT INTO IP_FLOOR(FLOOR_UID, FLOOR_TEXT, FLOOR_LOCATION, BUILDING_ID, ORG_ID)
select FLOOR_UID, FLOOR_TEXT, FLOOR_LOCATION, BUILDING_ID, @ORG_ID from IP_FLOOR where ORG_ID = 1

--- ward
INSERT INTO IP_WARD(WARD_UID, WARD_TEXT, WARD_LOCATION, FLOOR_ID, IS_ACTIVE, ORG_ID)
select WARD_UID, WARD_TEXT, WARD_LOCATION, FLOOR_ID, 1, @ORG_ID from IP_WARD where ORG_ID = 1

--- room type
INSERT INTO IP_ROOMTYPE(ROOMTYPE_UID, ROOMTYPE_TEXT, ITEM_ID, ORG_ID)
select ROOMTYPE_UID, ROOMTYPE_TEXT, ITEM_ID, @ORG_ID from IP_ROOMTYPE where ORG_ID = 1;

--- room
INSERT INTO IP_ROOM(ROOM_UID, ROOM_TEXT, ROOMTYPE_ID, WARD_ID, ORG_ID)
select ROOM_UID, ROOM_TEXT, ROOMTYPE_ID, WARD_ID, @ORG_ID from IP_ROOM where ORG_ID = 1

--- bed
INSERT INTO IP_BED(BED_UID, BED_TEXT, CAGE_ID, CAGE_NAME, ROOM_ID, IS_ACTIVE, BED_STATUS, ORG_ID)
select BED_UID, BED_TEXT, CAGE_ID, CAGE_NAME, ROOM_ID, 1, BED_STATUS, @ORG_ID from IP_BED where ORG_ID = 1

--- alergy
INSERT INTO PMS_ALLERGY(ALLERGY_UID, ALLERGY_NAME, ALLERGY_DESC, ORG_ID, IS_ACTIVE, CREATED_BY, CREATED_ON)
Select ALLERGY_UID, ALLERGY_NAME, ALLERGY_DESC, @ORG_ID, 1, 3, GETDATE() from PMS_ALLERGY where ORG_ID =1

--- admission reason
INSERT INTO IP_ADMISSION_REASON(REASON_UID, REASON_TEXT, REASON_LOCATION, AMOUNT, ORG_ID)
Select REASON_UID, REASON_TEXT, REASON_LOCATION, AMOUNT, @ORG_ID from IP_ADMISSION_REASON where ORG_ID = 1