CREATE OR REPLACE FUNCTION public.fnhos_earn(p_start_date date, p_end_date date, p_org_id bigint)
 RETURNS TABLE("CATEGORY" text, "SERIES" text, "VALUE" numeric)
 LANGUAGE sql
AS $function$
SELECT "CATEGORY", "SERIES", COALESCE("VALUE",0) AS "VALUE"--, "CVALUE", "CVALUE2"
FROM (
SELECT 
"RIS_SERVICETYPE"."SERVICE_TYPE_TEXT" AS "CATEGORY",
0 AS "SERIES",
sum (COALESCE("RIS_ORDERDTL"."RATE",0)) AS "VALUE"
--TO_CHAR(sum (COALESCE("RIS_ORDERDTL"."RATE",0)), '999,99,99,990D99') AS "CVALUE",
--trim(to_char(sum (COALESCE("RIS_ORDERDTL"."RATE",0)),'฿999,99,99,990D99')) AS "CVALUE2"
FROM 
"RIS_ORDER"
JOIN "RIS_ORDERDTL" 	ON "RIS_ORDER"."ORDER_ID" = "RIS_ORDERDTL"."ORDER_ID"
JOIN "RIS_EXAMRESULT"	ON "RIS_ORDERDTL"."ORDER_ID" = "RIS_EXAMRESULT"."ORDER_ID"
JOIN "RIS_EXAM"     	ON "RIS_ORDERDTL"."EXAM_ID" = "RIS_EXAM"."EXAM_ID"
JOIN "RIS_SERVICETYPE"  ON "RIS_SERVICETYPE"."SERVICE_TYPE_ID" = "RIS_ORDERDTL"."SERVICE_TYPE"
WHERE "RIS_ORDERDTL"."STATUS"= 'F' 
AND "RIS_ORDER"."ORG_ID" = p_org_id
AND ("RIS_EXAMRESULT"."FINALIZED_ON"::date between p_start_date and p_end_date)
GROUP BY "RIS_SERVICETYPE"."SERVICE_TYPE_TEXT"

UNION 

SELECT 
'Total Earning' AS "CATEGORY",
1 AS "SERIES",
sum (COALESCE("RIS_ORDERDTL"."RATE" ,0)) AS "VALUE"
--TO_CHAR(sum (COALESCE("RIS_ORDERDTL"."RATE",0)), '999,99,99,990D99') AS "CVALUE",
--trim(to_char(sum (COALESCE("RIS_ORDERDTL"."RATE",0)),'฿999,99,99,990D99')) AS "CVALUE2"
FROM 
"RIS_ORDER"
JOIN "RIS_ORDERDTL" 	ON "RIS_ORDER"."ORDER_ID" = "RIS_ORDERDTL"."ORDER_ID"
JOIN "RIS_EXAMRESULT"	ON "RIS_ORDERDTL"."ORDER_ID" = "RIS_EXAMRESULT"."ORDER_ID"
JOIN "RIS_EXAM"     	ON "RIS_ORDERDTL"."EXAM_ID" = "RIS_EXAM"."EXAM_ID"
JOIN "RIS_SERVICETYPE"  ON "RIS_SERVICETYPE"."SERVICE_TYPE_ID" = "RIS_ORDERDTL"."SERVICE_TYPE"
WHERE "RIS_ORDERDTL"."STATUS"= 'F' 
AND "RIS_ORDER"."ORG_ID" = p_org_id
AND ("RIS_EXAMRESULT"."FINALIZED_ON"::date between p_start_date and p_end_date)
) AS main 
ORDER BY "SERIES" desc, "CATEGORY"
$function$
;
