CREATE OR REPLACE FUNCTION public.fnhos_sitewiseexamtypepi(p_start_date date, p_end_date date, p_org_id bigint)
 RETURNS TABLE("CATEGORY" text, "SERIES" text, "VALUE" bigint)
 LANGUAGE sql
AS $function$
SELECT 
"RIS_EXAM"."EXAM_NAME" AS "CATEGORY",
'0' AS "SERIES",
count("RIS_ORDERDTL"."ACCESSION_NO") AS "VALUE"
FROM "RIS_ORDER"     	
JOIN "RIS_ORDERDTL"    ON "RIS_ORDER"."ORDER_ID" = "RIS_ORDERDTL"."ORDER_ID"
--JOIN "RIS_MODALITY"    ON "RIS_MODALITY"."MODALITY_ID" = "RIS_ORDERDTL"."MODALITY_ID" 
JOIN "RIS_EXAM"     	ON "RIS_ORDERDTL"."EXAM_ID" = "RIS_EXAM"."EXAM_ID"
JOIN "RIS_EXAMRESULT"  ON "RIS_ORDERDTL"."ORDER_ID" = "RIS_EXAMRESULT"."ORDER_ID"
JOIN "RIS_SERVICETYPE" ON "RIS_SERVICETYPE"."SERVICE_TYPE_ID" = "RIS_ORDERDTL"."SERVICE_TYPE"
WHERE "RIS_ORDERDTL"."STATUS"= 'F' 
AND "RIS_ORDER"."ORG_ID" = p_org_id
AND ("RIS_EXAMRESULT"."FINALIZED_ON"::date between p_start_date and p_end_date)
GROUP BY "RIS_EXAM"."EXAM_NAME"
ORDER BY "VALUE" DESC 
$function$
;