CREATE OR REPLACE FUNCTION public.fnhos_sitewisestudytypepi(p_start_date date, p_end_date date, p_org_id bigint)
 RETURNS TABLE("CATEGORY" text, "SERIES" text, "VALUE" bigint)
 LANGUAGE sql
AS $function$
SELECT 
"RIS_MODALITY"."MODALITY_NAME" AS "CATEGORY", --SERIES
'0' AS "SERIES",
count("RIS_ORDERDTL"."ACCESSION_NO") AS "VALUE" -- "VALUE" 
FROM "RIS_ORDER"     	
JOIN "RIS_ORDERDTL"    ON "RIS_ORDER"."ORDER_ID" = "RIS_ORDERDTL"."ORDER_ID"
JOIN "RIS_MODALITY"    ON "RIS_MODALITY"."MODALITY_ID" = "RIS_ORDERDTL"."MODALITY_ID" 
JOIN "RIS_EXAMRESULT" 	ON "RIS_ORDERDTL"."ORDER_ID" = "RIS_EXAMRESULT"."ORDER_ID"
WHERE 
"RIS_ORDERDTL"."STATUS"= 'F' 
AND "RIS_ORDER"."ORG_ID" =  p_org_id
AND ("RIS_EXAMRESULT"."FINALIZED_ON"::date BETWEEN p_start_date AND p_end_date)
GROUP BY "RIS_MODALITY"."MODALITY_NAME" 
ORDER BY "RIS_MODALITY"."MODALITY_NAME"
$function$
;