/* CREATE TABLE */

DECLARE @ORG_ID INT
SET @ORG_ID=1

/* CREATE TABLE */
IF OBJECT_ID('tempdb..#temp_MEASURE_UNIT') IS NOT NULL DROP TABLE #temp_MEASURE_UNIT

CREATE TABLE #temp_MEASURE_UNIT(
UNIT_CD VARCHAR(100),
NAME VARCHAR(100),
OMITTED_NAME VARCHAR(100),
CHOOSE_NAME VARCHAR(100),
DISP_NAME VARCHAR(100),
KANA_NAME VARCHAR(100),
EN_NAME VARCHAR(100),
CLS_CD VARCHAR(100),
VISIBLE_FLAG VARCHAR(100),
LIST_NUM VARCHAR(100),
FOREIGN_CD VARCHAR(100),
DELETE_DATE VARCHAR(100),
REG_NAME VARCHAR(100),
REGIST_DATE VARCHAR(100),
MOD_NAME VARCHAR(100),
UPDATE_DATE VARCHAR(100),
TIME_STAMP VARCHAR(100)
);

/* INSERT QUERY NO: 1 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"10"', '"times"', '"times"', '"times"', '"times"', '""', '""', '""', '"1"', '""', '"times"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 2 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"100"', '"bag"', '"bag"', '"bag"', '"bag"', '""', '""', '""', '"1"', '""', '"bag"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 3 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"110"', '"capsule"', '"capsule"', '"capsule"', '"capsule"', '""', '""', '""', '"1"', '""', '"capsule"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 4 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"120"', '"unit"', '"unit"', '"unit"', '"unit"', '""', '""', '""', '"1"', '""', '"unit"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 5 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"130"', '"L"', '"L"', '"L"', '"L"', '""', '""', '""', '"1"', '""', '"L"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 6 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"140"', '"Mg"', '"Mg"', '"Mg"', '"Mg"', '""', '""', '""', '"1"', '""', '"Mg"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 7 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"150"', '"ml"', '"ml"', '"ml"', '"ml"', '""', '""', '""', '"1"', '""', '"ml"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 8 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"160"', '"sheet"', '"sheet"', '"sheet"', '"sheet"', '""', '""', '""', '"1"', '""', '"sheet"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 9 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"170"', '"Syringe"', '"Syringe"', '"Syringe"', '"Syringe"', '""', '""', '""', '"1"', '""', '"Syringe"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 10 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"180"', '"V"', '"V"', '"V"', '"V"', '""', '""', '""', '"1"', '""', '"V"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 11 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"20"', '"A"', '"A"', '"A"', '"A"', '""', '""', '""', '"1"', '""', '"A"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 12 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"200"', '"tube"', '"tube"', '"tube"', '"tube"', '""', '""', '""', '"1"', '""', '"tube"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 13 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"210"', '"mLV"', '"mLV"', '"mLV"', '"mLV"', '""', '""', '""', '"1"', '""', '"mLV"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 14 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"220"', '"Kit"', '"Kit"', '"Kit"', '"Kit"', '""', '""', '""', '"1"', '""', '"Kit"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 15 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"230"', '"cylinder"', '"cylinder"', '"cylinder"', '"cylinder"', '""', '""', '""', '"1"', '""', '"cylinder"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 16 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"240"', '"tablet"', '"tablet"', '"tablet"', '"tablet"', '""', '""', '""', '"1"', '""', '"tablet"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 17 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"30"', '"bottle"', '"bottle"', '"bottle"', '"bottle"', '""', '""', '""', '"1"', '""', '"bottle"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 18 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"40"', '"set"', '"set"', '"set"', '"set"', '""', '""', '""', '"1"', '""', '"set"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 19 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"50"', '"box"', '"box"', '"box"', '"box"', '""', '""', '""', '"1"', '""', '"box"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 20 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"60"', '"hour"', '"hour"', '"hour"', '"hour"', '""', '""', '""', '"1"', '""', '"hour"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 21 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"70"', '"minute"', '"minute"', '"minute"', '"minute"', '""', '""', '""', '"1"', '""', '"minute"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 22 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"80"', '"g"', '"g"', '"g"', '"g"', '""', '""', '""', '"1"', '""', '"g"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 23 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"90"', '"needle"', '"needle"', '"needle"', '"needle"', '""', '""', '""', '"1"', '""', '"needle"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 24 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"190"', '"T"', '"T"', '"T"', '"T"', '""', '""', '""', '"1"', '"190"', '"T"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 25 */
INSERT INTO #temp_MEASURE_UNIT(UNIT_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"250"', '"organ"', '"organ"', '"organ"', '"organ"', '""', '""', '""', '"1"', '"250"', '"organ"', '""', '""', '""', '""', '""', '""'
);

INSERT INTO  MEASURING_UNIT (MEASURING_UNIT_UID,[NAME],SHORT_NAME,DISPLAY_RANK,ORG_ID)
SELECT CONCAT('M',REPLACE(UNIT_CD, '"', '')) as MEASURING_UNIT_UID,REPLACE([NAME], '"', '')as [NAME],REPLACE(DISP_NAME, '"', '') as DISP_NAME,1 as DISPLAY_RANK,@ORG_ID as ORG_ID FROM #temp_MEASURE_UNIT






