/* CREATE TABLE */


DECLARE @ORG_ID INT
SET @ORG_ID=1

/* CREATE TABLE */
IF OBJECT_ID('tempdb..#temp_Patient_Type') IS NOT NULL DROP TABLE #temp_Patient_Type

CREATE TABLE #temp_Patient_Type(
PATIENT_DIV VARCHAR(100),
NAME VARCHAR(100),
OMITTED_NAME VARCHAR(100),
CHOOSE_NAME VARCHAR(100),
DISP_NAME VARCHAR(100),
KANA_NAME VARCHAR(100),
EN_NAME VARCHAR(100),
CLS_CD VARCHAR(100),
VISIBLE_FLAG VARCHAR(100),
LIST_NUM VARCHAR(100),
FOREIGN_CD VARCHAR(100),
DELETE_DATE VARCHAR(100),
REG_NAME VARCHAR(100),
REGIST_DATE VARCHAR(100),
MOD_NAME VARCHAR(100),
UPDATE_DATE VARCHAR(100),
TIME_STAMP VARCHAR(100)
);

/* INSERT QUERY NO: 1 */
INSERT INTO #temp_Patient_Type(PATIENT_DIV, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"10"', '"No pacemaker"', '"No pacemaker"', '"No pacemaker"', '"No pacemaker"', '""', '""', '""', '"1"', '"10"', '""', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 2 */
INSERT INTO #temp_Patient_Type(PATIENT_DIV, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"20"', '"Pacemaker attached"', '"Pacemaker attached"', '"Pacemaker attached"', '"Pacemaker attached"', '""', '""', '""', '"1"', '"20"', '""', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 3 */
INSERT INTO #temp_Patient_Type(PATIENT_DIV, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, CLS_CD, VISIBLE_FLAG, LIST_NUM, FOREIGN_CD, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"30"', '"Pacemaker unknown"', '"Pacemaker unknown"', '"Pacemaker unknown"', '"Pacemaker unknown"', '""', '""', '""', '"1"', '"30"', '""', '""', '""', '""', '""', '""', '""'
);

INSERT INTO  PATIENT_TYPE(PATIENT_TYPE_UID,PATIENT_TYPE_NAME,DISPLAY_NAME, DISPLAY_RANK,ORG_ID) 
SELECT CONCAT('P',REPLACE(PATIENT_DIV, '"', ''))as TECHNIQUE_UID ,REPLACE([NAME], '"', '')as TECHNIQUE_NAME,REPLACE(DISP_NAME, '"', '') as DISPLAY_NAME,1 as DISPLAY_RANK, @ORG_ID as ORG_ID FROM #temp_Patient_Type

