DECLARE @ORG_ID INT
SET @ORG_ID=1
INSERT INTO REQUEST_TYPE(REQUEST_TYPE_UID,REQUEST_TYPE_NAME,SHORT_NAME,DISPLAY_NAME,ORG_ID) VALUES
('RT001','Normal','Normal','Normal',@ORG_ID),
('RT002','Stat','Stat','Stat',@ORG_ID),
('RT003','Urgent','Urgent','Urgent',@ORG_ID)