CREATE TABLE TECHNIQUE(
	TECHNIQUE_ID INT  PRIMARY KEY IDENTITY,
	TECHNIQUE_NAME NVARCHAR(100),
	
	TECHNIQUE_UID NVARCHAR(100),
	DISPLAY_NAME NVARCHAR(500),
	DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
	IS_ACTIVE BIT DEFAULT 1,
	IS_DELETED BIT DEFAULT 0,
	ORG_ID INT NULL,
	CREATED_BY INT NULL,
	CREATED_ON [DATETIME] NULL,
	LAST_MODIFIED_BY INT NULL,
	LAST_MODIFIED_ON [DATETIME] NULL)

CREATE TABLE MEASURING_UNIT(
    MEASURING_UNIT_ID INT  PRIMARY KEY IDENTITY,
	NAME NVARCHAR(500),
	SHORT_NAME NVARCHAR(100),

  MEASURING_UNIT_UID NVARCHAR(100),
	DISPLAY_NAME NVARCHAR(500),
	DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
	IS_ACTIVE BIT DEFAULT 1,
	IS_DELETED BIT DEFAULT 0,
	ORG_ID INT NULL,
	CREATED_BY INT NULL,
	CREATED_ON [DATETIME] NULL,
	LAST_MODIFIED_BY INT NULL,
	LAST_MODIFIED_ON [DATETIME] NULL)

CREATE TABLE TECHNIQUE_DTL(
    TECHNIQUE_DTL_ID INT PRIMARY KEY IDENTITY,
	TECHNIQUE_DTL_NAME NVARCHAR(100),
	TECHNIQUE_ID INT, --forign key
	MEASURING_UNIT_ID INT, --forign key 

	TECHNIQUE_DTL_UID NVARCHAR(100),
	DISPLAY_NAME NVARCHAR(500),
	DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
	IS_ACTIVE BIT DEFAULT 1,
	IS_DELETED BIT DEFAULT 0,
	ORG_ID INT NULL,
	CREATED_BY INT NULL,
	CREATED_ON [DATETIME] NULL,
	LAST_MODIFIED_BY INT NULL,
	LAST_MODIFIED_ON [DATETIME] NULL,
  
  CONSTRAINT FK_TECHNIQUE_DTL_TECHNIQUE FOREIGN KEY (TECHNIQUE_ID)
        REFERENCES TECHNIQUE (TECHNIQUE_ID),
  CONSTRAINT FK_TECHNIQUE_DTL_MEASURING_UNIT FOREIGN KEY (MEASURING_UNIT_ID)
        REFERENCES MEASURING_UNIT  (MEASURING_UNIT_ID),
	)

CREATE TABLE CLINICAL_DIAGNOSIS(
        CLINICAL_DIAGNOSIS_ID INT  PRIMARY KEY IDENTITY,
		CLINICAL_DIAGNOSIS_NAME   NVARCHAR(500),
		SHORT_NAME  NVARCHAR(100),

		CLINICAL_DIAGNOSIS_UID NVARCHAR(100),
		DISPLAY_NAME NVARCHAR(500),
		DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
		IS_ACTIVE BIT DEFAULT 1,
		IS_DELETED BIT DEFAULT 0,
		ORG_ID INT NULL,
		CREATED_BY INT NULL,
		CREATED_ON [DATETIME] NULL,
		LAST_MODIFIED_BY INT NULL,
		LAST_MODIFIED_ON [DATETIME] NULL
 )

 

 CREATE TABLE CLINICAL_FINDING(
        CLINICAL_FINDING_ID INT  PRIMARY KEY IDENTITY,
		CLINICAL_FINDING_NAME   NVARCHAR(500),
		SHORT_NAME  NVARCHAR(100),

		CLINICAL_FINDING_UID NVARCHAR(100),
		DISPLAY_NAME NVARCHAR(500),
		DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
		IS_ACTIVE BIT DEFAULT 1,
		IS_DELETED BIT DEFAULT 0,
		ORG_ID INT NULL,
		CREATED_BY INT NULL,
		CREATED_ON [DATETIME] NULL,
		LAST_MODIFIED_BY INT NULL,
		LAST_MODIFIED_ON [DATETIME] NULL
 )
		
	

 CREATE TABLE STUDY_PURPOSE(
        STUDY_PURPOSE_ID INT  PRIMARY KEY IDENTITY,
		STUDY_PURPOSE_NAME   NVARCHAR(500),
		SHORT_NAME  NVARCHAR(100),

		STUDY_PURPOSE_UID NVARCHAR(100),
		DISPLAY_NAME NVARCHAR(500),
		DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
		IS_ACTIVE BIT DEFAULT 1,
		IS_DELETED BIT DEFAULT 0,
		ORG_ID INT NULL,
		CREATED_BY INT NULL,
		CREATED_ON [DATETIME] NULL,
		LAST_MODIFIED_BY INT NULL,
		LAST_MODIFIED_ON [DATETIME] NULL
 )


 CREATE TABLE STUDY_REGION(
        STUDY_REGION_ID INT  PRIMARY KEY IDENTITY,
	    STUDY_REGION_NAME   NVARCHAR(500),
		SHORT_NAME  NVARCHAR(100),

		STUDY_REGION_UID NVARCHAR(100),
		DISPLAY_NAME NVARCHAR(500),
		DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
		IS_ACTIVE BIT DEFAULT 1,
		IS_DELETED BIT DEFAULT 0,
		ORG_ID INT NULL,
		CREATED_BY INT NULL,
		CREATED_ON [DATETIME] NULL,
		LAST_MODIFIED_BY INT NULL,
		LAST_MODIFIED_ON [DATETIME] NULL
 )

 

 CREATE TABLE CHEIF_COMPLAINT(
        CHEIF_COMPLAINT_ID INT  PRIMARY KEY IDENTITY,
	    CHEIF_COMPLAINT_NAME   NVARCHAR(500),
		SHORT_NAME  NVARCHAR(100),

		CHEIF_COMPLAINT_UID NVARCHAR(100),
		DISPLAY_NAME NVARCHAR(500),
		DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
		IS_ACTIVE BIT DEFAULT 1,
		IS_DELETED BIT DEFAULT 0,
		ORG_ID INT NULL,
		CREATED_BY INT NULL,
		CREATED_ON [DATETIME] NULL,
		LAST_MODIFIED_BY INT NULL,
		LAST_MODIFIED_ON [DATETIME] NULL
 )

 CREATE TABLE PATIENT_PREPARATION(
        PATIENT_PREPARATION_ID INT  PRIMARY KEY IDENTITY,
	    PATIENT_PREPARATION_NAME   NVARCHAR(500),
		SHORT_NAME  NVARCHAR(100),

		PATIENT_PREPARATION_UID NVARCHAR(100),
		DISPLAY_NAME NVARCHAR(500),
		DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
		IS_ACTIVE BIT DEFAULT 1,
		IS_DELETED BIT DEFAULT 0,
		ORG_ID INT NULL,
		CREATED_BY INT NULL,
		CREATED_ON [DATETIME] NULL,
		LAST_MODIFIED_BY INT NULL,
		LAST_MODIFIED_ON [DATETIME] NULL
 )
	

	CREATE TABLE REQUEST_TYPE(
        REQUEST_TYPE_ID INT  PRIMARY KEY IDENTITY,
	    REQUEST_TYPE_NAME   NVARCHAR(500),
		SHORT_NAME  NVARCHAR(100),

		REQUEST_TYPE_UID NVARCHAR(100),
		DISPLAY_NAME NVARCHAR(500),
		DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
		IS_ACTIVE BIT DEFAULT 1,
		IS_DELETED BIT DEFAULT 0,
		ORG_ID INT NULL,
		CREATED_BY INT NULL,
		CREATED_ON [DATETIME] NULL,
		LAST_MODIFIED_BY INT NULL,
		LAST_MODIFIED_ON [DATETIME] NULL
 )


 	CREATE TABLE  NURSING_CLASS(
        NURSING_CLASS_ID INT  PRIMARY KEY IDENTITY,
	    NURSING_CLASS_NAME   NVARCHAR(500),
		SHORT_NAME  NVARCHAR(100),

		NURSING_CLASS_UID NVARCHAR(100),
		DISPLAY_NAME NVARCHAR(500),
		DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
		IS_ACTIVE BIT DEFAULT 1,
		IS_DELETED BIT DEFAULT 0,
		ORG_ID INT NULL,
		CREATED_BY INT NULL,
		CREATED_ON [DATETIME] NULL,
		LAST_MODIFIED_BY INT NULL,
		LAST_MODIFIED_ON [DATETIME] NULL
 )


 CREATE TABLE  AMBULATORY_CLASS(
        AMBULATORY_CLASS_ID INT  PRIMARY KEY IDENTITY,
	    AMBULATORY_CLASS_NAME   NVARCHAR(500),
		SHORT_NAME  NVARCHAR(100),

		AMBULATORY_CLASS_UID NVARCHAR(100),
		DISPLAY_NAME NVARCHAR(500),
		DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
		IS_ACTIVE BIT DEFAULT 1,
		IS_DELETED BIT DEFAULT 0,
		ORG_ID INT NULL,
		CREATED_BY INT NULL,
		CREATED_ON [DATETIME] NULL,
		LAST_MODIFIED_BY INT NULL,
		LAST_MODIFIED_ON [DATETIME] NULL
 )



 CREATE TABLE   PATIENT_TYPE(
        PATIENT_TYPE_ID INT  PRIMARY KEY IDENTITY,
	    PATIENT_TYPE_NAME   NVARCHAR(500),
		SHORT_NAME  NVARCHAR(100),

		PATIENT_TYPE_UID NVARCHAR(100),
		DISPLAY_NAME NVARCHAR(500),
		DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
		IS_ACTIVE BIT DEFAULT 1,
		IS_DELETED BIT DEFAULT 0,
		ORG_ID INT NULL,
		CREATED_BY INT NULL,
		CREATED_ON [DATETIME] NULL,
		LAST_MODIFIED_BY INT NULL,
		LAST_MODIFIED_ON [DATETIME] NULL
 )

 --Alert level can be 1. Always, 2. Appointment 3. Arrival 4. Reporting
 CREATE TABLE   KNOWN_DISEASE(
        KNOWN_DISEASE_ID INT  PRIMARY KEY IDENTITY,
	    KNOWN_DISEASE_NAME   NVARCHAR(500),
		SHORT_NAME  NVARCHAR(100),
		SHOW_ALERT NVARCHAR(100),
		ALERT_LEVEL NVARCHAR(100),

		PATIENT_TYPE_UID NVARCHAR(100),
		DISPLAY_NAME NVARCHAR(500),
		DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
		IS_ACTIVE BIT DEFAULT 1,
		IS_DELETED BIT DEFAULT 0,
		ORG_ID INT NULL,
		CREATED_BY INT NULL,
		CREATED_ON [DATETIME] NULL,
		LAST_MODIFIED_BY INT NULL,
		LAST_MODIFIED_ON [DATETIME] NULL
 )

 
 --Alert level can be 1. Always, 2. Appointment 3. Arrival 4. Reporting
 CREATE TABLE   KNOWN_DISORDER(
        KNOWN_DISORDER_ID INT  PRIMARY KEY IDENTITY,
	    KNOWN_DISORDER_NAME   NVARCHAR(500),
		SHORT_NAME  NVARCHAR(100),
		SHOW_ALERT NVARCHAR(100),
		ALERT_LEVEL NVARCHAR(100),

		KNOWN_DISORDER_UID NVARCHAR(100),
		DISPLAY_NAME NVARCHAR(500),
		DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
		IS_ACTIVE BIT DEFAULT 1,
		IS_DELETED BIT DEFAULT 0,
		ORG_ID INT NULL,
		CREATED_BY INT NULL,
		CREATED_ON [DATETIME] NULL,
		LAST_MODIFIED_BY INT NULL,
		LAST_MODIFIED_ON [DATETIME] NULL
 )


 CREATE TABLE   SPECIAL_INSTRUCTION (
        SPECIAL_INSTRUCTION_ID INT  PRIMARY KEY IDENTITY,
	    SPECIAL_INSTRUCTION_NAME   NVARCHAR(500),
		SHORT_NAME  NVARCHAR(100),
		SHOW_ALERT NVARCHAR(100),
		ALERT_LEVEL NVARCHAR(100),

		SPECIAL_INSTRUCTION_UID NVARCHAR(100),
		DISPLAY_NAME NVARCHAR(500),
		DISPLAY_RANK INT CHECK (DISPLAY_RANK >=1 AND DISPLAY_RANK <=4),
		IS_ACTIVE BIT DEFAULT 1,
		IS_DELETED BIT DEFAULT 0,
		ORG_ID INT NULL,
		CREATED_BY INT NULL,
		CREATED_ON [DATETIME] NULL,
		LAST_MODIFIED_BY INT NULL,
		LAST_MODIFIED_ON [DATETIME] NULL
 )

--ALTER TABLE [dbo].[PMS_ALLERGY] add SHORT_NAME  NVARCHAR(100)
--ALTER TABLE [dbo].[PMS_ALLERGY] add SHOW_ALERT NVARCHAR(100)
--ALTER TABLE [dbo].[PMS_ALLERGY] add	ALERT_LEVEL NVARCHAR(100)
--ALTER TABLE [dbo].[PMS_ALLERGY] add IS_DELETED BIT DEFAULT 0

