/* CREATE TABLE */

DECLARE @ORG_ID INT
SET @ORG_ID=1

/* CREATE TABLE */
IF OBJECT_ID('tempdb..#temp_Specail_Ins') IS NOT NULL DROP TABLE #temp_Specail_Ins

CREATE TABLE #temp_Specail_Ins(
SPECIAL_INST_CD VARCHAR(100),
NAME VARCHAR(100),
OMITTED_NAME VARCHAR(100),
CHOOSE_NAME VARCHAR(100),
DISP_NAME VARCHAR(100),
KANA_NAME VARCHAR(100),
EN_NAME VARCHAR(100),
VISIBLE_FLAG VARCHAR(100),
LIST_NUM VARCHAR(100),
DELETE_DATE VARCHAR(100),
REG_NAME VARCHAR(100),
REGIST_DATE VARCHAR(100),
MOD_NAME VARCHAR(100),
UPDATE_DATE VARCHAR(100),
TIME_STAMP VARCHAR(100)
);

/* INSERT QUERY NO: 1 */
INSERT INTO #temp_Specail_Ins(SPECIAL_INST_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, VISIBLE_FLAG, LIST_NUM, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"10"', '"No"', '"No"', '"No"', '"No"', '""', '""', '"1"', '"10"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 2 */
INSERT INTO #temp_Specail_Ins(SPECIAL_INST_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, VISIBLE_FLAG, LIST_NUM, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"20"', '"Claustrophobia"', '"Claustrophobia"', '"Claustrophobia"', '"Claustrophobia"', '""', '""', '"1"', '"20"', '""', '""', '""', '""', '""', '""'
);

/* INSERT QUERY NO: 3 */
INSERT INTO #temp_Specail_Ins(SPECIAL_INST_CD, NAME, OMITTED_NAME, CHOOSE_NAME, DISP_NAME, KANA_NAME, EN_NAME, VISIBLE_FLAG, LIST_NUM, DELETE_DATE, REG_NAME, REGIST_DATE, MOD_NAME, UPDATE_DATE, TIME_STAMP)
VALUES
(
'"30"', '"The insertion is presumed to be difficult."', '"The insertion is presumed to be difficult. "', '"The insertion is presumed to be difficult."', '"The insertion is presumed to be difficult."', '""', '""', '"1"', '"30"', '""', '""', '""', '""', '""', '""'
);


INSERT INTO  SPECIAL_INSTRUCTION(SPECIAL_INSTRUCTION_UID,SPECIAL_INSTRUCTION_NAME,DISPLAY_NAME, DISPLAY_RANK,ORG_ID) 
SELECT CONCAT('SI',REPLACE(SPECIAL_INST_CD, '"', ''))as TECHNIQUE_UID ,REPLACE([NAME], '"', '')as TECHNIQUE_NAME,REPLACE(DISP_NAME, '"', '') as DISPLAY_NAME,1 as DISPLAY_RANK, @ORG_ID as ORG_ID FROM #temp_Specail_Ins
