CREATE OR REPLACE FUNCTION public.fnreport_imagerankpi(p_start_date date, p_end_date date, p_org_id text, p_exam_type_id bigint, p_user_id bigint)
 RETURNS TABLE("EXAMTYPEGOV" text, "REVIEW" text, "VALUE" bigint)
 LANGUAGE sql
AS $function$ --CT Image Review
SELECT
(SELECT "EXAM_TYPE_TEXT" FROM "RIS_EXAMTYPE" WHERE "EXAM_TYPE_ID" =  "GOVT"."EXAM_TYPE") AS "EXAMTYPEGOV",
(SELECT "EXAMIMAGEQUALITY_NAME" FROM "RIS_EXAMIMAGEQUALITY" WHERE "RIS_EXAMIMAGEQUALITY"."EXAMIMAGEQUALITY_ID"= "RIS_EXAMRESULT"."EXAMIMAGEQUALITY_ID") AS "REVIEW",
count ("RIS_EXAMRESULT"."EXAMIMAGEQUALITY_ID") AS "VALUE"
FROM "RIS_ORDERDTL" 
JOIN "RIS_EXAMRESULT" ON ("RIS_ORDERDTL"."ORDER_ID" = "RIS_EXAMRESULT"."ORDER_ID")
JOIN "RIS_EXAM" ON ("RIS_ORDERDTL"."EXAM_ID" = "RIS_EXAM"."EXAM_ID")
JOIN "RIS_EXAM" "GOVT" ON ("GOVT"."EXAM_ID" = "RIS_EXAM"."GOVT_ID"::integer)
WHERE 
(p_org_id IS null or ("RIS_ORDERDTL"."ORG_ID" = ANY(SELECT(regexp_split_to_table(p_org_id, ','))::INTEGER)))  --1,2,3
AND ("RIS_EXAMRESULT"."FINALIZED_BY" = p_user_id OR p_user_id IS NULL)
AND ("RIS_ORDERDTL"."CREATED_ON"::date BETWEEN p_start_date AND p_end_date)
AND ("GOVT"."EXAM_TYPE" = p_exam_type_id OR p_exam_type_id IS NULL)
AND ("RIS_ORDERDTL"."STATUS" = 'F') 
AND ("RIS_EXAMRESULT"."EXAMIMAGEQUALITY_ID" IS NOT NULL)
GROUP BY "RIS_EXAMRESULT"."EXAMIMAGEQUALITY_ID","GOVT"."EXAM_TYPE"
ORDER BY 1,2
$function$
;
--select * from fnreport_imagerankpi ('2023-03-01','2023-03-20','4,36',1);