CREATE OR REPLACE FUNCTION public.fnreport_scorerankpi(p_start_date date, p_end_date date, p_org_id text, p_service_type bigint)
RETURNS TABLE("REVIEW" text, "VALUE" bigint)
LANGUAGE sql
AS $function$ --Scoring Review
SELECT 
CASE WHEN "RIS_ORDERCLINICALSIGNIFICANCE"."CLINICAL_SIGNIFICANCE_UID" ILIKE '' THEN "RIS_ORDERCLINICALSIGNIFICANCE"."CLINICAL_SIGNIFICANCE_ID"::TEXT ELSE "RIS_ORDERCLINICALSIGNIFICANCE"."CLINICAL_SIGNIFICANCE_UID" END AS "REVIEW",
count ("RIS_ORDERCLINICALSIGNIFICANCE"."CLINICAL_SIGNIFICANCE_ID") AS "VALUE"
FROM "RIS_ORDERDTL" 
JOIN "RIS_EXAMRESULT" ON ("RIS_ORDERDTL"."ORDER_ID" = "RIS_EXAMRESULT"."ORDER_ID")
JOIN "RIS_ORDERCLINICALSIGNIFICANCE" ON ("RIS_ORDERCLINICALSIGNIFICANCE"."CLINICAL_SIGNIFICANCE_ID" = "RIS_EXAMRESULT"."CLINICAL_SIGNIFICANCE_ID")
WHERE 
(p_org_id IS null or ("RIS_ORDERDTL"."ORG_ID" = ANY(SELECT(regexp_split_to_table(p_org_id, ','))::INTEGER)))  --1,2,3
AND ("RIS_ORDERDTL"."CREATED_ON"::date BETWEEN p_start_date AND p_end_date)
AND ("RIS_ORDERDTL"."SERVICE_TYPE" = p_service_type OR p_service_type IS NULL)
AND ("RIS_ORDERDTL"."STATUS" = 'F')
GROUP BY "RIS_ORDERCLINICALSIGNIFICANCE"."CLINICAL_SIGNIFICANCE_UID", "RIS_ORDERCLINICALSIGNIFICANCE"."CLINICAL_SIGNIFICANCE_ID"
ORDER BY "RIS_ORDERCLINICALSIGNIFICANCE"."CLINICAL_SIGNIFICANCE_ID"
$function$
;

--SELECT * FROM public.fnreport_scorerankpi ('2023-03-01', '2023-03-28', '4,36', NULL)