CREATE OR REPLACE FUNCTION public.fncomplicationpi(p_start_date date, p_end_date date)
RETURNS TABLE("CATEGORY" text, "VALUE" bigint)
LANGUAGE sql
AS $function$
SELECT 
CASE WHEN "COMPLICATION" = 1 THEN 'Complicated' ELSE 'Normal' END AS "CATEGORY",
count("ORDER_ID") AS "VALUE"
FROM (
SELECT 
"PMR_ORDER"."ORG_ID",
"PMR_ORDER"."ORDER_ID",
"PMR_SCHEDULE"."PHYSICIAN_ID",
CASE WHEN "PMR_RPT_COMPLICATIONS"."COMPLICATIONS_ID" IS NULL THEN 0 ELSE 1 END AS "COMPLICATION"
FROM 
"PMR_ORDER" 
JOIN "PMR_ORDERDTL" ON ("PMR_ORDER"."ORDER_ID" = "PMR_ORDERDTL"."ORDER_ID" AND "PMR_ORDERDTL"."IS_ACTIVE" = TRUE)
JOIN "PMR_STUDY_REPORT" ON ("PMR_ORDERDTL"."ACCESSION_NO" = "PMR_STUDY_REPORT"."ACCESSION_NO" AND "PMR_STUDY_REPORT"."IS_LATEST" = true)
JOIN "PMR_SCHEDULE" ON ("PMR_SCHEDULE"."SCHEDULE_ID"= "PMR_ORDER"."SCHEDULE_ID")
LEFT JOIN "PMR_RPT_COMPLICATIONS" ON ("PMR_RPT_COMPLICATIONS"."ACCESSION_NO"= "PMR_ORDERDTL"."ACCESSION_NO" AND "PMR_RPT_COMPLICATIONS"."COMPLICATIONS_TEXT" ILIKE '%yes%')
LEFT JOIN (SELECT count("ORDER_EXAMINATION_TEAM_ID") "team", "ORDER_ID"  FROM "PMR_EXAMINATION_TEAM" WHERE  "IS_ACTIVE" = true AND "IS_PRIMARY_DOCTOR" = FALSE AND "JOB_TYPE_ID" != 9  GROUP BY "ORDER_ID") "PMR_EXAMINATION_TEAM" ON ("PMR_EXAMINATION_TEAM"."ORDER_ID" = "PMR_ORDER"."ORDER_ID")
WHERE 
"PMR_ORDER"."IS_ACTIVE" = TRUE
AND ("PMR_ORDER"."ORDER_DT"::DATE BETWEEN p_start_date AND p_end_date )
AND ("PMR_STUDY_REPORT"."REPORT_STATUS" = 'F') 
) AS "main" GROUP BY "COMPLICATION"
$function$
;


--SELECT * FROM fncomplicationpi ('2022-01-01', '2023-04-01')