-- FUNCTION: public.fndatewisestudytypesbar(date, date, text)

-- DROP FUNCTION IF EXISTS public.fndatewisestudytypesbar(date, date, text);

CREATE OR REPLACE FUNCTION public.fndatewisestudytypesbar(
	p_start_date date,
	p_end_date date,
	p_status text)
    RETURNS TABLE("CATEGORY" text, "SERIES" text, "VALUE" bigint) 
    LANGUAGE 'sql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
SELECT 
"PMS_CHARGABLE"."ITEM_NAME" AS "STUDY_NAME", --CATEGORY
CASE WHEN "PMR_STUDY_REPORT"."REPORT_STATUS" = 'F' THEN 'Finalized' ELSE 'Draft' END AS "REPORT_STATUS", --SERIES
count ("PMS_CHARGABLE"."ITEM_NAME") AS "VALUE" --VALUE
FROM 
"PMR_ORDER"
JOIN "PMR_ORDERDTL" ON ("PMR_ORDER"."ORDER_ID" = "PMR_ORDERDTL"."ORDER_ID" AND "PMR_ORDERDTL"."IS_ACTIVE" = TRUE)
JOIN "PMS_CHARGABLE" ON ("PMR_ORDERDTL"."ITEM_ID" = "PMS_CHARGABLE"."ITEM_ID" AND "PMS_CHARGABLE"."IS_ACTIVE" = TRUE)
JOIN (SELECT "VERSION_NO", "PMR_STUDY_REPORT"."ACCESSION_NO", "PMR_STUDY_REPORT"."REPORT_STATUS" FROM "PMR_STUDY_REPORT" WHERE "PMR_STUDY_REPORT"."IS_ACTIVE" = TRUE) AS "PMR_STUDY_REPORT" ON ("PMR_ORDERDTL"."ACCESSION_NO" = "PMR_STUDY_REPORT"."ACCESSION_NO" AND "PMR_STUDY_REPORT"."VERSION_NO" = (SELECT MAX("PMR_STUDY_REPORT"."VERSION_NO") FROM "PMR_STUDY_REPORT" WHERE "PMR_STUDY_REPORT"."ACCESSION_NO" = "PMR_ORDERDTL"."ACCESSION_NO"))
WHERE  
"PMR_ORDER"."IS_ACTIVE" = TRUE
AND ("PMR_ORDER"."ORDER_DT"::DATE BETWEEN p_start_date AND p_end_date)
AND ("PMR_STUDY_REPORT"."REPORT_STATUS" = p_status OR p_status='0')
GROUP BY "PMS_CHARGABLE"."ITEM_NAME","PMR_STUDY_REPORT"."REPORT_STATUS"
ORDER BY "STUDY_NAME", "REPORT_STATUS"
$BODY$;

ALTER FUNCTION public.fndatewisestudytypesbar(date, date, text)
    OWNER TO postgres;
