-- FUNCTION: public.fnendoscopistworkloadbar(date, date, text)

-- DROP FUNCTION IF EXISTS public.fnendoscopistworkloadbar(date, date, text);

CREATE OR REPLACE FUNCTION public.fnendoscopistworkloadbar(
	p_start_date date,
	p_end_date date,
	p_status text)
    RETURNS TABLE("CATEGORY" text, "SERIES" text, "VALUE" bigint) 
    LANGUAGE 'sql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
SELECT  
(CASE 
WHEN "GBL_ENV"."DOCTOR_NAME_FORMAT" = '[[T]] [[F]] [[L]]' THEN (COALESCE("HR_USER"."TITLE",'') || ' ' || "HR_USER"."FNAME" || ' ' || "HR_USER"."LNAME")
WHEN "GBL_ENV"."DOCTOR_NAME_FORMAT" = '[[T]] [[L]] [[F]]' THEN (COALESCE("HR_USER"."TITLE",'') || ' ' || "HR_USER"."LNAME" || ' ' || "HR_USER"."FNAME")
WHEN "GBL_ENV"."DOCTOR_NAME_FORMAT" = '[[F]] [[T]] [[L]]' THEN ("HR_USER"."FNAME" || ' ' || COALESCE("HR_USER"."TITLE",'') || ' ' || "HR_USER"."LNAME")
WHEN "GBL_ENV"."DOCTOR_NAME_FORMAT" = '[[F]] [[L]] [[T]]' THEN ("HR_USER"."FNAME" || ' ' || "HR_USER"."LNAME" || ' ' || COALESCE("HR_USER"."TITLE",''))
WHEN "GBL_ENV"."DOCTOR_NAME_FORMAT" = '[[L]] [[T]] [[F]]' THEN ("HR_USER"."LNAME" || ' ' || COALESCE("HR_USER"."TITLE",'') || ' ' || "HR_USER"."FNAME")
WHEN "GBL_ENV"."DOCTOR_NAME_FORMAT" = '[[L]] [[F]] [[T]]' THEN ("HR_USER"."LNAME" || ' ' || "HR_USER"."FNAME" || ' ' || COALESCE("HR_USER"."TITLE",''))
ELSE (COALESCE("HR_USER"."TITLE",'') || ' ' || "HR_USER"."FNAME" || ' ' || "HR_USER"."LNAME")
END) AS "CATEGORY",
"PMS_CHARGABLE"."ITEM_NAME" AS "SERIES",
count ("PMS_CHARGABLE"."ITEM_NAME") as "VALUE"
FROM 
"PMR_ORDER"
JOIN "PMR_ORDERDTL" ON "PMR_ORDER"."ORDER_ID" = "PMR_ORDERDTL"."ORDER_ID"
JOIN "PMR_EXAMINATION_TEAM" ON ("PMR_ORDER"."ORDER_ID" = "PMR_EXAMINATION_TEAM"."ORDER_ID" AND "PMR_EXAMINATION_TEAM"."IS_ACTIVE" = TRUE AND "PMR_EXAMINATION_TEAM"."JOB_TYPE_ID" IS NOT NULL AND "PMR_EXAMINATION_TEAM"."JOB_TYPE_ID" != 9 )
JOIN (SELECT 
(CASE WHEN (SELECT "DOCTOR_NAME_LANG" FROM "GBL_ENV" WHERE "ORG_ID" = 15) = 'E' THEN "TITLE_ENG" ELSE "TITLE_NLS" END)  "TITLE",
(CASE WHEN (SELECT "DOCTOR_NAME_LANG" FROM "GBL_ENV" WHERE "ORG_ID" = 15) = 'E' THEN "FNAME_ENG" ELSE "FNAME_NLS" END)  "FNAME",
(CASE WHEN (SELECT "DOCTOR_NAME_LANG" FROM "GBL_ENV" WHERE "ORG_ID" = 15) = 'E' THEN "LNAME_ENG" ELSE "LNAME_NLS" END)  "LNAME",
* FROM "HR_USER" WHERE "HR_USER"."IS_ACTIVE" = TRUE ) AS "HR_USER" ON ("PMR_EXAMINATION_TEAM"."USER_ID" = "HR_USER"."USER_ID")
JOIN "GBL_ENV" ON ("PMR_ORDER"."ORG_ID" = "GBL_ENV"."ORG_ID" AND "GBL_ENV"."ORG_ID" = 15 )
JOIN (SELECT "VERSION_NO", "PMR_STUDY_REPORT"."ACCESSION_NO", "PMR_STUDY_REPORT"."REPORT_STATUS" FROM "PMR_STUDY_REPORT" WHERE "PMR_STUDY_REPORT"."IS_ACTIVE" = TRUE) AS "PMR_STUDY_REPORT" ON ("PMR_ORDERDTL"."ACCESSION_NO" = "PMR_STUDY_REPORT"."ACCESSION_NO" AND "PMR_STUDY_REPORT"."VERSION_NO" = (SELECT MAX("PMR_STUDY_REPORT"."VERSION_NO") FROM "PMR_STUDY_REPORT" WHERE "PMR_STUDY_REPORT"."ACCESSION_NO" = "PMR_ORDERDTL"."ACCESSION_NO"))
JOIN "PMS_CHARGABLE" ON ("PMR_ORDERDTL"."ITEM_ID" = "PMS_CHARGABLE"."ITEM_ID" AND "PMS_CHARGABLE"."IS_ACTIVE" = TRUE)
WHERE 
"PMR_ORDER"."IS_ACTIVE" = TRUE
AND ("PMR_ORDER"."ORDER_DT"::DATE BETWEEN p_start_date::date AND p_end_date::date )
AND ("PMR_STUDY_REPORT"."REPORT_STATUS" = p_status OR p_status IS NULL)
AND ("HR_USER"."JOB_TYPE" = 'D')
GROUP BY "PMS_CHARGABLE"."ITEM_NAME","GBL_ENV"."DOCTOR_NAME_FORMAT","HR_USER"."TITLE","HR_USER"."FNAME","HR_USER"."LNAME"
ORDER BY "CATEGORY","SERIES","VALUE"
$BODY$;

ALTER FUNCTION public.fnendoscopistworkloadbar(date, date, text)
    OWNER TO postgres;
